/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.forms;

import biblioteca.cats.*;
import biblioteca.items.Item;
import biblioteca.items.Libro;
import biblioteca.items.Revista;
import biblioteca.persistencia.Archivo;
import java.util.ArrayList;
import ui.models.ListaModeloCategorias;
import ui.models.ModeloItem;

/**
 *
 * @author francisco
 */
public class MainWindows extends javax.swing.JFrame {

    private Item itemSeleccionado;

    /**
     * Creates new form MainWindows
     */
    public MainWindows() {
        initComponents();

        Archivo.cargar();
        cargarCategorias();
        actualizar();

    }

    private void actualizar() {
        Categoria categoriaSeleccionada = (Categoria) lstCategorias.getSelectedValue();
        if (categoriaSeleccionada == null) {
            tblItems.setModel(new ModeloItem(Archivo.getDatos().getItems().filtrar(txtBuscar.getText())));
        } else {
            tblItems.setModel(new ModeloItem(categoriaSeleccionada.filtrar(txtBuscar.getText())));
        }
    }

    private void cargarCategorias() {
        lstCategorias.setModel(new ListaModeloCategorias());
        lstCategoriasSeleccionar.setModel(new ListaModeloCategorias());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanelBuscar = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jSplitPaneMain = new javax.swing.JSplitPane();
        jPanelCategorias = new javax.swing.JPanel();
        jPanelAgregarCategorias = new javax.swing.JPanel();
        txtAgregarCategoria = new javax.swing.JTextField();
        btnAgregarCategoria = new javax.swing.JButton();
        btnEliminarCategoria = new javax.swing.JButton();
        jScrollPaneCategorias = new javax.swing.JScrollPane();
        lstCategorias = new javax.swing.JList();
        jSplitPaneSecondary = new javax.swing.JSplitPane();
        jScrollPaneItems = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        jPanelItems = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelLibro = new javax.swing.JPanel();
        txtLibroTitulo = new javax.swing.JTextField();
        txtLibroAutor = new javax.swing.JTextField();
        txtLibroEditorial = new javax.swing.JTextField();
        lblLibroTitulo = new javax.swing.JLabel();
        lblLibroAutor = new javax.swing.JLabel();
        lblEditorial = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        btnAgregarLibro = new javax.swing.JButton();
        btnGuardarLibro = new javax.swing.JButton();
        jPanelRevista = new javax.swing.JPanel();
        jPanelAudio = new javax.swing.JPanel();
        jPanelDVD = new javax.swing.JPanel();
        jScrollPaneCategoriasSeleccionar = new javax.swing.JScrollPane();
        lstCategoriasSeleccionar = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jPanelBuscar.setLayout(new javax.swing.BoxLayout(jPanelBuscar, javax.swing.BoxLayout.LINE_AXIS));

        lblBuscar.setText("Buscar:  ");
        jPanelBuscar.add(lblBuscar);

        txtBuscar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtBuscar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        jPanelBuscar.add(txtBuscar);

        jToolBar1.add(jPanelBuscar);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jSplitPaneMain.setResizeWeight(1.0);

        txtAgregarCategoria.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtAgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarCategoriaActionPerformed(evt);
            }
        });

        btnAgregarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/img/new_category.png"))); // NOI18N
        btnAgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCategoriaActionPerformed(evt);
            }
        });

        btnEliminarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/img/delete.png"))); // NOI18N
        btnEliminarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAgregarCategoriasLayout = new javax.swing.GroupLayout(jPanelAgregarCategorias);
        jPanelAgregarCategorias.setLayout(jPanelAgregarCategoriasLayout);
        jPanelAgregarCategoriasLayout.setHorizontalGroup(
            jPanelAgregarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgregarCategoriasLayout.createSequentialGroup()
                .addComponent(txtAgregarCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarCategoria)
                .addGap(6, 6, 6))
        );
        jPanelAgregarCategoriasLayout.setVerticalGroup(
            jPanelAgregarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAgregarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnAgregarCategoria)
            .addComponent(btnEliminarCategoria)
        );

        lstCategorias.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstCategorias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstCategorias.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCategoriasValueChanged(evt);
            }
        });
        jScrollPaneCategorias.setViewportView(lstCategorias);

        javax.swing.GroupLayout jPanelCategoriasLayout = new javax.swing.GroupLayout(jPanelCategorias);
        jPanelCategorias.setLayout(jPanelCategoriasLayout);
        jPanelCategoriasLayout.setHorizontalGroup(
            jPanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAgregarCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPaneCategorias)
        );
        jPanelCategoriasLayout.setVerticalGroup(
            jPanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoriasLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanelAgregarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
        );

        jSplitPaneMain.setLeftComponent(jPanelCategorias);

        jSplitPaneSecondary.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemsMouseClicked(evt);
            }
        });
        jScrollPaneItems.setViewportView(tblItems);

        jSplitPaneSecondary.setTopComponent(jScrollPaneItems);

        jPanelItems.setLayout(new javax.swing.BoxLayout(jPanelItems, javax.swing.BoxLayout.LINE_AXIS));

        jPanelLibro.setPreferredSize(new java.awt.Dimension(892, 150));

        lblLibroTitulo.setText("Titulo");

        lblLibroAutor.setText("Autor");

        lblEditorial.setText("Editorial");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/img/book.png"))); // NOI18N

        jToolBar2.setRollover(true);

        btnAgregarLibro.setText("+");
        btnAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLibroActionPerformed(evt);
            }
        });
        jToolBar2.add(btnAgregarLibro);

        btnGuardarLibro.setText("Save");
        btnGuardarLibro.setEnabled(false);
        btnGuardarLibro.setFocusable(false);
        btnGuardarLibro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardarLibro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarLibroActionPerformed(evt);
            }
        });
        jToolBar2.add(btnGuardarLibro);

        javax.swing.GroupLayout jPanelLibroLayout = new javax.swing.GroupLayout(jPanelLibro);
        jPanelLibro.setLayout(jPanelLibroLayout);
        jPanelLibroLayout.setHorizontalGroup(
            jPanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addGroup(jPanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEditorial)
                    .addComponent(lblLibroTitulo)
                    .addComponent(lblLibroAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLibroTitulo)
                    .addComponent(txtLibroAutor)
                    .addComponent(txtLibroEditorial))
                .addContainerGap())
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelLibroLayout.setVerticalGroup(
            jPanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLibroLayout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLibroLayout.createSequentialGroup()
                        .addGap(0, 191, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(jPanelLibroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLibroTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLibroTitulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLibroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLibroAutor))
                        .addGap(8, 8, 8)
                        .addGroup(jPanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLibroEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEditorial))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane.addTab("Libro", jPanelLibro);

        jPanelRevista.setPreferredSize(new java.awt.Dimension(892, 150));

        javax.swing.GroupLayout jPanelRevistaLayout = new javax.swing.GroupLayout(jPanelRevista);
        jPanelRevista.setLayout(jPanelRevistaLayout);
        jPanelRevistaLayout.setHorizontalGroup(
            jPanelRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        jPanelRevistaLayout.setVerticalGroup(
            jPanelRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Revista", jPanelRevista);

        jPanelAudio.setPreferredSize(new java.awt.Dimension(892, 150));

        javax.swing.GroupLayout jPanelAudioLayout = new javax.swing.GroupLayout(jPanelAudio);
        jPanelAudio.setLayout(jPanelAudioLayout);
        jPanelAudioLayout.setHorizontalGroup(
            jPanelAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        jPanelAudioLayout.setVerticalGroup(
            jPanelAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Audio", jPanelAudio);

        jPanelDVD.setPreferredSize(new java.awt.Dimension(892, 150));

        javax.swing.GroupLayout jPanelDVDLayout = new javax.swing.GroupLayout(jPanelDVD);
        jPanelDVD.setLayout(jPanelDVDLayout);
        jPanelDVDLayout.setHorizontalGroup(
            jPanelDVDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        jPanelDVDLayout.setVerticalGroup(
            jPanelDVDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("DVD", jPanelDVD);

        jSplitPane1.setLeftComponent(jTabbedPane);

        lstCategoriasSeleccionar.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstCategoriasSeleccionar.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCategoriasSeleccionarValueChanged(evt);
            }
        });
        jScrollPaneCategoriasSeleccionar.setViewportView(lstCategoriasSeleccionar);

        jSplitPane1.setRightComponent(jScrollPaneCategoriasSeleccionar);

        jPanelItems.add(jSplitPane1);

        jSplitPaneSecondary.setBottomComponent(jPanelItems);

        jSplitPaneMain.setRightComponent(jSplitPaneSecondary);

        getContentPane().add(jSplitPaneMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        // TODO add your handling code here:
        actualizar();
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void lstCategoriasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCategoriasValueChanged
        // TODO add your handling code here:
        actualizar();
    }//GEN-LAST:event_lstCategoriasValueChanged

    private void btnEliminarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCategoriaActionPerformed
        // TODO add your handling code here:
        Categoria catEliminar = (Categoria) lstCategorias.getSelectedValue();
        if (catEliminar != null && !catEliminar.getNombre().equals("Default")) {
            Archivo.getDatos().getCategorias().remove(catEliminar);
            Archivo.guardar();
            cargarCategorias();
        }
    }//GEN-LAST:event_btnEliminarCategoriaActionPerformed

    private void btnAgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCategoriaActionPerformed
        // TODO add your handling code here:
        if (!txtAgregarCategoria.getText().equals("") && Archivo.getDatos().getCategorias().filtrar(txtAgregarCategoria.getText()).size() == 0) {
            Archivo.getDatos().getCategorias().add(new Categoria(txtAgregarCategoria.getText()));
            cargarCategorias();
            Archivo.guardar();
        }
    }//GEN-LAST:event_btnAgregarCategoriaActionPerformed

    private void txtAgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgregarCategoriaActionPerformed

    private void lstCategoriasSeleccionarValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCategoriasSeleccionarValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstCategoriasSeleccionarValueChanged

    private void btnAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLibroActionPerformed
        // TODO add your handling code here:
        itemSeleccionado = null;
        btnGuardarLibro.setEnabled(true);

    }//GEN-LAST:event_btnAgregarLibroActionPerformed

    private void btnGuardarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarLibroActionPerformed
        // TODO add your handling code here:
        Libro l = (Libro) (itemSeleccionado);
        if (l == null) {
            l = new Libro(null, null, null);
            Archivo.getDatos().getItems().add(l);
        }
        ListaCategoria lc= Archivo.getDatos().getCategorias();
        for( Categoria c: lc){
            l.borrarCategoria(c);
        }
        for( Object c: lstCategoriasSeleccionar.getSelectedValuesList()){
            l.agregarCategoria((Categoria)c);
        }
        l.setTitulo(txtLibroTitulo.getText());
        l.setAutor(txtLibroAutor.getText());
        l.setEditorial(txtLibroEditorial.getText());
        Archivo.guardar();
        btnGuardarLibro.setEnabled(false);
        actualizar();
    }//GEN-LAST:event_btnGuardarLibroActionPerformed

    private void tblItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemsMouseClicked
        // TODO add your handling code here:
        Item i = ((ModeloItem) tblItems.getModel()).getItem(tblItems.getSelectedRow());
        itemSeleccionado=i;
        if (i != null) {
            if(i instanceof Libro){
                Libro l = (Libro)i;
                jTabbedPane.setSelectedIndex(0);
                txtLibroAutor.setText(l.getAutor());
                txtLibroTitulo.setText(l.getTitulo());
                txtLibroEditorial.setText(l.getEditorial());
                btnGuardarLibro.setEnabled(true);
                
            }else if(i instanceof Revista){
                jTabbedPane.setSelectedIndex(1);
            }
            //JOptionPane.showMessageDialog(this, i, "Información del Adicional", JOptionPane.INFORMATION_MESSAGE);
            ArrayList<Integer> catSel=new ArrayList<Integer>();
            for(Categoria c: i.getCategorias()){
                catSel.add(Archivo.getDatos().getCategorias().indexOf(c));
            }
            int []icatSel = new int[catSel.size()];
            for(int j=0;j<catSel.size();j++){
                icatSel[j]=catSel.get(j);
            }
            lstCategoriasSeleccionar.setSelectedIndices(icatSel);
            
        }
    }//GEN-LAST:event_tblItemsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCategoria;
    private javax.swing.JButton btnAgregarLibro;
    private javax.swing.JButton btnEliminarCategoria;
    private javax.swing.JButton btnGuardarLibro;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelAgregarCategorias;
    private javax.swing.JPanel jPanelAudio;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JPanel jPanelCategorias;
    private javax.swing.JPanel jPanelDVD;
    private javax.swing.JPanel jPanelItems;
    private javax.swing.JPanel jPanelLibro;
    private javax.swing.JPanel jPanelRevista;
    private javax.swing.JScrollPane jScrollPaneCategorias;
    private javax.swing.JScrollPane jScrollPaneCategoriasSeleccionar;
    private javax.swing.JScrollPane jScrollPaneItems;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPaneMain;
    private javax.swing.JSplitPane jSplitPaneSecondary;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblLibroAutor;
    private javax.swing.JLabel lblLibroTitulo;
    private javax.swing.JList lstCategorias;
    private javax.swing.JList lstCategoriasSeleccionar;
    private javax.swing.JTable tblItems;
    private javax.swing.JTextField txtAgregarCategoria;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtLibroAutor;
    private javax.swing.JTextField txtLibroEditorial;
    private javax.swing.JTextField txtLibroTitulo;
    // End of variables declaration//GEN-END:variables
}
